### ISSUE TITLE
Page for editing the documents leads to a 404 page[BUG] 

### ISSUE THREAD

**Issue by MysteryTopHat** [Mocha-Downloader/mocha-downloader#53]
Clicking the edit button on the docs site (https://mocha-downloader.github.io/docs/intro/) takes you to an error page and a 404 error code. Here is one example link https://github.com/mocha-downloader/mocha-downloader.github.io/edit/main/website/docs/1-intro.md. There is no page to be found regardless of the section that you try to click on the documentation site.

**Comment by developomp** [comment]
moved to: https://github.com/Mocha-Downloader/mocha-downloader.github.io/issues/2
