### ISSUE TITLE
[Feature Request] Allow user to choose where the video is downloaded onto ther computer

### ISSUE THREAD

**Issue by MysteryTopHat** [Mocha-Downloader/mocha-downloader#66]
After something has finished processing, a popup should open asking the user where they want to save the file on there computer. Here is an example window from downloading a video from discord. 

![image](https://user-images.githubusercontent.com/69489030/147620876-dbdc879d-36e5-4f59-b40d-8f08291f737f.png)

**Comment by developomp** [comment]
Mocha Downloader is designed to be portable and so all files generated by it (configuration file, downloaded files, logs, etc.) are placed in one folder (the `mocha` folder).
